services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\AiLabel\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Enum/*'

  B13\AiLabel\DataProcessing\AiLabelProcessor:
    tags:
      - { name: 'data.processor', identifier: 'ai-label' }
